workflows:
  flutter-app:
    name: Flutter App Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:ricaliveofficial@gmail.com
        recipients:
          - your@email.com